# Generated by Django 5.1 on 2026-02-28 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="story",
            name="status",
            field=models.CharField(
                choices=[
                    ("processing", "Processing"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                default="processing",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="story",
            name="title",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
